config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/saber/detail", to: "home#index"
  get "/saber/search", to: "home#index"
  get "/saber/index", to: "home#index"

  get "/test/", to: "test#index"
  get "/test/child", to: "test#child"
  get "/article/", to: "article#index"
  get "/article/:id", to: "article#show"
  get "/article/:id/update", to: "article#update"
  post "/article/publish", to: "article#publish"
  get "/tag/", to: "article#tag_index"
  get "/tag/:name", to: "article#tag"
  post "/search/", to: "search#do_search"
  post "/search/app", to: "search#app_search"
  get "/search/", to: "search#no_result"
  get "/shishen/", to: "card#index"
  get "/shishen/:id", to: "card#show"

  #app
  get "/app/card/:id", to: "app#card"
  get "/app/card_ssr", to: "app#card_ssr"
  get "/app/card_sr", to: "app#card_sr"
  get "/app/card_r", to: "app#card_r"

  get "/app/article_gonglve", to: "app#article_gonglve"
  get "/app/article_news", to: "app#article_news"
  get "/app/article_wenda", to: "app#article_wenda"
  get "/app/article/:id", to: "app#article", id: /\d+/
  get "/app/tag/:name", to: "app#tag"

  get "/app/jubao", to: "app#jubao"
  get "/app/hot", to: "app#hot"

  #diyquan
  post "/refreshCookies", to: "diyquan#refresh_cookies"
  get "/getOperElements", to: "diyquan#get_categories"
  get "/getHomeCouponList", to: "diyquan#get_coupons_index"
  get "/getFenleiCouponList", to: "diyquan#get_coupons_fenlei"
  get "/getSearchCouponList", to: "diyquan#get_coupons_search"
  get "/getHotCouponList", to: "diyquan#get_coupons_hot"
  get "/getK9CouponList", to: "diyquan#get_coupons_k9"
  get "/getK20CouponList", to: "diyquan#get_coupons_k20"

  get "/getLanlanHomeCouponList", to: "diyquan#get_lanlan_coupons_index"
  get "/getLanlanFenleiCouponList", to: "diyquan#get_lanlan_coupons_fenlei"
  get "/getLanlanSearchCouponList", to: "diyquan#get_lanlan_coupons_search"

  get "/youhui/:id", to: "diyquan#get_coupon_by_id", id: /\d+/
  get "/zk/:id", to: "diyquan#old_zk", id: /\d+/
  get "/buy/:id", to: "diyquan#buy", id: /\d+/
  get "/zhuanchang/:id", to: "diyquan#zhuanchang", id: /\d+/
  get "/fenlei/:pinyin", to: "diyquan#fenlei"
  get "/zhekou/:keyword/", to: "diyquan#zhekou"
  get "/zhekou/:keyword/rexiao/", to: "diyquan#zhekou_rexiao"
  get "/zhekou/:keyword/tejia/", to: "diyquan#zhekou_tejia"
  get "/zhekou/:keyword/dae/", to: "diyquan#zhekou_dae"
  get "/zhekou/:keyword/yizhe/", to: "diyquan#zhekou_yizhe"
  get "/query/", to: "diyquan#search"

  get "/query/noresult", to: "diyquan#noresult"
  get "/baokuan/", to: "diyquan#baokuan"
  get "/9kuai9/", to: "diyquan#k9"
  get "/shikuaigou/", to: "diyquan#k20"

  get "/dianpu/", to: "dianpu#map_s"
  get "/dianpu/:nick/", to: "dianpu#show"
  get "/dianpu_buy/:seller_id/", to: "dianpu#buy"
  
  #html sitemap
  get "/map_k/", to: "diyquan#map_k"
  get "/map_k/:page", to: "diyquan#map_k"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iquan.rb
class ProductClick < ApplicationRecord
  self.table_name = 'iquan_product_clicks'
end

class Link < ApplicationRecord
  self.table_name = 'shikuai_links'
end

class SuggestKeyword < ApplicationRecord
  self.table_name = 'iquan_suggest_keywords'
end

class CidKeywordRelation < ApplicationRecord
  self.table_name = 'iquan_coupon_keyword_relations'
end

class Shop < ApplicationRecord
  self.table_name = 'iquan_shops'
end

class ShopCoupon < ApplicationRecord
  self.table_name = 'iquan_shop_coupons'
end

class Product < ApplicationRecord
  self.table_name = 'iquan_products'
end

class CouponSuggestion < ApplicationRecord
  self.table_name = 'iquan_coupon_suggestions'
end

class CateCollection < ApplicationRecord
  self.table_name = 'iquan_cate_collections'
end

class SearchResult < ApplicationRecord
  self.table_name = 'iquan_search_results'
end

app/controllers/application_controller.rb
require 'net/http'
require 'iquan'
require 'zkapi/zk_api'
require 'zkapi/lanlan_api'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def is_robot?
    user_agent = request.headers["HTTP_USER_AGENT"]
    user_agent.present? && user_agent =~ /(bot|spider|slurp|Linux x86_64)/i
  end

  def is_device_mobile?
    user_agent = request.headers["HTTP_USER_AGENT"]
    user_agent.present? && user_agent =~ /\b(Android|iPhone|Windows Phone|Opera Mobi|Kindle|BackBerry|PlayBook|UCWEB|Mobile)\b/i
  end
  def redirect_pc_to_mobile
    if request.host == 'pc domain' && is_device_mobile?
      redirect_to "http://mobile domain#{request.path}"
    end
  end
  def not_found
    raise ActionController::RoutingError.new('NOT FOUND')
  end
  def is_keyword_url?(keyword)
    keyword =~ /(http|taobao|tmall)/i
  end

  def get_tb_id(url)
    m = url.match(/id=(\d+)/i)
    return m[1] if m
    nil
  end

  def get_suggest_keywords_new(keyword)
    begin
      sk = SuggestKeyword.where(keyword: keyword).take
      return [] if sk.nil?
      sk.sks.split(',')
    rescue
      return []
    end
  end
end

app/controllers/dianpu_controller.rb
class DianpuController < ApplicationController
  def show
    @shop = Shop.where(nick: params[:nick]).take
    not_found if @shop.nil?
    @dsr_info = JSON.parse(@shop.dsr_info)
    ind = JSON.parse(@dsr_info["dsrStr"])["ind"]
    @desc = "#{@shop.title}是一家经营信誉良好、获得消费者广泛好评的一家#{@shop.is_tmall == 1 ? '天猫' : '淘宝'}店铺。店铺掌柜为#{@shop.nick}，如果大家有任何关于#{@shop.title}的问题，都可以向其进行咨询。店铺的注册地点在#{@shop.provcity}，全国包邮哦，看到合适的宝贝赶快拍下，#{@shop.provcity}附近的朋友们可能在当天就收到快递喽。#{@shop.title}在售的宝贝有#{@shop.totalsold}件，有木有很多！近30天的销量为#{@shop.procnt}件，代掌柜#{@shop.nick}感谢大家的大力支持。#{@shop.title}主营类目为#{ind}，具体有#{@shop.main_auction}，欢迎大家选购。#{@shop.title}的综合评分还是不错的，在宝贝描述相符、服务态度、物流服务上均在平均水平之上，大家可以放心选购自己心仪的宝贝。
还在等什么？快去#{@shop.title}逛一逛~"
    @items = JSON.parse(@shop.auctions_inshop.empty? || @shop.auctions_inshop == 'null' ? "[]" : @shop.auctions_inshop)
    @hot_coupons = get_static_coupons('static_hot_coupons')
    @suggest_keywords = get_suggest_keywords_new(@shop.search_keyword)
    @path = "#{request.path}/"
    @shops = Shop.where("id > ?", @shop.id).order("id").select(:nick,:pic_url,:title).limit(15)
    @scoupons = ShopCoupon.where(seller_id: @shop.source_id).to_a
    render "show", layout: "diyquan"
  end

  def buy
    redirect_to "https://market.m.taobao.com/apps/aliyx/coupon/detail.html?wh_weex=true&activity_id=#{params[:activity_id]}&seller_id=#{params[:seller_id]}", status: 302
  end

  def map_s
    @page = params[:page].to_i
    @page = @page == 0 ? 0 : @page - 1
    @shops = Shop.order("id desc").limit(1000).offset(1000 * @page).select(:title, :nick).to_a
    not_found if @shops.size.zero?
    if @page > 0
      @title = "淘宝天猫旗舰店排行榜_爱券网_第#{@page}页"
    else
      @title = "淘宝天猫旗舰店排行榜_爱券网"
    end
    @total_page = @page + 20
    @title = "淘宝天猫旗舰店排行榜-女装男装居家数码美妆箱包"
    @h1 = "淘宝天猫旗舰店排行榜"
    @keywords = "天猫旗舰店,淘宝店铺,淘宝店铺大全,淘宝店铺排行榜"
    @description = "淘宝天猫旗舰店排行榜，女装、男装、居家、数码、美妆、箱包、母婴、宠物、配饰等多种类别的淘宝天猫店铺大排行，淘宝天猫店铺用户评价，卖的商品怎么样？店铺打折信息，内部优惠券，这里都查得到 - 十块购"
    @path = "/dianpu/"
    render "map_s", layout: "diyquan"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title = "")
    content_for :title, page_title.to_s
  end
  def keywords(page_keywords = "")
    content_for :keywords, page_keywords.to_s
  end
  def head_desc(page_description = "")
    content_for :head_desc, page_description.to_s
  end
  def mobile_url(path)
    content_for :mobile_url, "#{path}"
  end
  def path(path)
    content_for :path, path
  end
  def h1(h1)
    content_for :h1, h1
  end
  def disable_turbolinks?(disable = false)
    content_for :disable_turbolinks, disable ? 'data-no-turbolink' : ''
  end
end

app/views/dianpu/_shop_bread.html.haml
- home_anchor = ['淘宝优惠券','淘宝内部优惠券','十块购','淘宝券'].sample
%p.bread-area
  %span 淘宝优惠券：
  %a{href: "/", title: "#{home_anchor}"} #{home_anchor}
  %span &nbsp;&nbsp;#{">"}&nbsp;&nbsp;
  %a{href: "/dianpu/", title: "淘宝店铺排行榜"} 淘宝店铺排行榜
  %span &nbsp;&nbsp;#{">"}&nbsp;&nbsp;
  %span #{title}

app/views/dianpu/map_s.html.haml
- title(@title)
- head_desc(@description)
- keywords(@keywords)
- path(@path)
- mobile_url(@path)
- h1(@h1)

= render partial: "diyquan/header_fenlei_zhekou"
.hori-cate-area
  .hot-keywords
    .wrapper
      - @shops.each do |shop|
        %a{href: "/dianpu/#{URI.encode(shop.nick)}/", title: "#{shop.title}"} #{shop.title}
      - (@page..@total_page).to_a.each do |page|
        %a{href: "/dianpu/?page=#{page}"} #{page}

= render partial: "diyquan/footer"

app/views/dianpu/show.html.haml
- title("【#{@shop.title}】#{@shop.title}优惠券/折扣/首页/评价怎么样")
- head_desc("#{@desc}")
- keywords("#{@shop.title},#{@shop.title}首页,#{@shop.title}优惠券,#{@shop.title}折扣,#{@shop.title}怎么样,#{@shop.title}评价,#{@shop.title}淘宝,#{@shop.title}天猫")
- path(@path)
- mobile_url(@path)
- h1("#{@shop.title}")

- if @suggest_keywords.size > 0
  = render partial: "diyquan/suggest_keywords", locals: {keywords: @suggest_keywords}

.wrapper.zk-detail
  .wrapper-l.zk-main
    = render partial: "dianpu/shop_bread", locals: {title: @shop.title}
    .shop
      .shop-cover
        %img.shop-cover-img{src:"#{@shop.pic_url}", alt: "#{@shop.title}"}
        %p.shop-cover-p 
          %strong #{@shop.title}
      .shop-info
        %p.shop-info-h1 #{@shop.title}
        %p.shop-desc 
          - if @scoupons.size > 0
            %strong #{@shop.title}
            正在发放的优惠券共有#{@scoupons.size}张：
            %br
            - @scoupons.each do |sc|
              #{@shop.title}满#{sc.m_price}元减#{sc.coupon_price}元优惠券 - 有效期至#{Time.at(sc.end_time).strftime("%Y-%m-%d %H:%M")} - 
              %a{href: "/dianpu_buy/#{sc.seller_id}/?activity_id=#{sc.activity_id}", title: "#{@shop.title}#{sc.coupon_price}元优惠券", style: "color:blue", target: "_blank"} 点我领取
              %br
          #{@desc}
        %p.sno
          #{@shop.title}在售商品：
          - @items.each do |item|
            #{item["title"].html_safe}，价格：#{item["price"]}元；
        .shop-buy
          %a.shop-buy-a{href: "/",title: "#{@shop.title}", rel: "nofollow"} 去看看
  .wrapper-r
    .rel-zk-area{style: "margin-top: 60px"}
      %p.head
        %span 正在热销
        %a.more-his{href: "/baokuan/", title: "淘宝爆款"} 去抢热门券 - GO
      .hot-zk-list.clearfix.swiper-container.swiper-container-horizontal
        .swiper-wrapper
          - swiper_count = @hot_coupons.size / 4
          - (0..swiper_count-1).each do |num|
            .swiper-slide
              - @hot_coupons[num * 4, 4].each do |coupon|
                %a{href: "/youhui/#{coupon['coupon_id']}/", title: "#{coupon['title']}", class: "zk-img-item"}
                  %img.lazy{data: {original: "#{coupon['thumbnail_pic']}"}, alt: "#{coupon['title']}", style: "opacity: 1;"}

.wrapper
  .rel-zk-area{style: "margin-bottom: 30px;"}
    %p.head
      %span 推荐店铺
    .rel-zk-list.clearfix
      - @shops.each do |shop|
        .shop-item
          %a{href: "/dianpu/#{URI.encode(shop.nick)}/", title: "#{shop.title}"}
            %img.shop-item-img{src: "#{shop.pic_url}", alt: "#{shop.title}"}
            %p.shop-item-p #{shop.title}

.wrapper
  .rel-zk-area{style: "margin-bottom: 30px;"}
    %p.head
      %span 热门优惠券
    .rel-zk-list.clearfix
      = render partial: "diyquan/quan_list", locals: {coupons: @hot_coupons}

= render partial: "diyquan/quan_detail_js"
= render partial: "diyquan/footer"

app/views/diyquan/_footer.html.haml
.footer
  .footer-top
    .wrapper
      .yl
        %p.head 友情链接：
        .yl-links
          %a{href: "/map_k/"} 天天特价9块9 
          %a{href: "/dianpu/"} 淘宝店铺排行榜
          - if @path
            %a{href: "http://m.shikuaigou.com#{@path}"} 移动页
      .logo-slogan
        .qr-code
          %a{href: "/"}
            %img{src: "/image/love.jpg"}
        .txt
          %p.s1 一定要加入搜藏呦！
          %p.s2 
  .footer-bootom
    .wrapper
      %p 十块购 - 渝ICP备15000671号-13

app/views/diyquan/_header_shoucang.html.erb
<header id="header" class="header">

  <div class="header-bar">
    <i class="close"></i>
    <div class="wrapper">
      <p class="coll-desc">按<strong>Ctrl&nbsp;+&nbsp;D</strong>,把十块购放入收藏夹，今日特价， 天天特价！</p>
    </div>
  </div>

  <div class="header-top">
    <div class="wrapper">
      <a class="logo-area" href="/" style="margin-top:25px">
        <img src="/image/logo.png" alt="十块购" style="width:240px">
      </a>
      <div class="slogan-area">
        <i class="slogan-icon slogan-icon-1"></i>
        <p>正品好货</p>
        <i class="slogan-icon slogan-icon-2"></i>
        <p>人工精选</p>
        <i class="slogan-icon slogan-icon-3"></i>
        <p>专享优惠券</p>
        <i class="slogan-icon slogan-icon-4"></i>
        <p>全场包邮</p>
      </div>
      <div class="search-area">
        <div class="input-area"><i></i><input class="search-input unfocus" type="text" value="输入关键词"></div>
        <a href="javascript:;" class="search-btn">搜索</a>
        <p class="err-tip"><i class="err-tip-icon"></i>亲，请复制宝贝全称进行搜索~<i class="arr-up"></i></p>
      </div>
    </div>
  </div>
  <div class="tab-area-plh">
    <div class="tab-area">
      <div class="wrapper">
        <div class="cate-area">
          <a data-ga-event="头部:点击:头部_精选推荐" href="/" class="cate-item jxtj active"><span class="cate-rec"></span></a>
          <a id="header_baokuan" data-ga-event="头部:点击:头部_爆款热销" href="/baokuan/" class="cate-item hot">爆款热销</a>
          <a id="header_k9" data-ga-event="头部:点击:头部_9块9包邮" href="/9kuai9/" class="cate-item">9块9包邮</a>
          <a id="header_k20" data-ga-event="头部:点击:头部_20元封顶" href="/shikuaigou/" class="cate-item">20元封顶</a>
          <a id="header_k20" data-ga-event="头部:点击:头部_领券直播" href="http://taobao.zhequan.cc/index.php?r=l&u=550416" class="cate-item" target="_blank">领券直播</a>
        </div>
        <div class="search-area">
          <i></i>
          <input class="search-input unfocus" type="text" value="输入关键词">
          <p class="err-tip"><i class="err-tip-icon"></i>亲，请复制宝贝全称进行搜索~<i class="arr-up"></i></p>
        </div>
      </div>

      <div class="hori-cate-area">
        <div class="cate-l-1">
          <div class="wrapper ">

            <a class="" href="/fenlei/nvzhuang/">女装</a>

            <a class="" href="/fenlei/nanzhuang/">男装</a>

            <a class="" href="/fenlei/xiezi/">鞋子</a>

            <a class="" href="/fenlei/xiangbao/">箱包</a>

            <a class="" href="/fenlei/meizhuang/">美妆</a>

            <a class="" href="/fenlei/hufu/">护肤</a>

            <a class="" href="/fenlei/shenghuo/">生活</a>

            <a class="" href="/fenlei/jujia/">居家</a>

            <a class="" href="/fenlei/meishi/">美食</a>

            <a class="" href="/fenlei/neiyi/">内衣</a>

            <a class="" href="/fenlei/yundong/">运动</a>

            <a class="" href="/fenlei/shuma/">数码</a>

            <a class="" href="/fenlei/muying/">母婴</a>

            <a class="" href="/fenlei/peishi/">配饰</a>

            <a class="" href="/fenlei/chengren/">成人</a>

            <a class="" href="/fenlei/chongwu/">宠物</a>

          </div>
        </div>
      </div>

    </div>
  </div>
</header>
<script type="text/javascript">
$(function(){
  var headerBar = $('.header-bar'),
  tabArea = $('#header .tab-area'),
  si = $('.search-input'),
  errTip = $('.err-tip'),
  sb = $('.search-btn');

  headerBar.find('.close').on('click',function(){
    headerBar.remove();
    var d = new Date();
    d.setTime(d.getTime()+(24*60*60*1000));
    $.cookie('hideHeaderBar',1,{
      path:'/',
      expires:d
    });
  });


  $(document).on('scroll',function(){
    var _top = $(document).scrollTop();
    if(_top >= 400){
      tabArea.addClass('fixed');
    }else{
      tabArea.removeClass('fixed');
    }
  });

  si.on('focus',function(){
    if($(this).val() == '输入关键词'){
      si.val('');
    }
    $(this).removeClass('unfocus');
  }).on('blur',function(){
    if($(this).val() == ''){
      si.val('输入关键词');
    }
    $(this).addClass('unfocus');
  }).on('keyup',function(e){
    var keycode = e.keyCode,
    q = $(this).val();

    $('.search-input.unfocus').val(q);

    if(keycode == 13 && q.trim()){
      goSearch(q.trim());
    }
    if(q.trim().match(/http|\.tmall|\.taobao/)){
      errTip.show();
    }else{
      errTip.hide();
    }
  });

  sb.on('click',function(){
    var q = $(si[0]).val();
    if(q.trim() && q.trim() != '输入关键词'){
      goSearch(q.trim());
    }
  });

  function goSearch(q){
    if(q.match(/http|\.tmall|\.taobao/)){
      return;
    }
    window.location.href = '/zhekou/' + encodeURIComponent(q) + '/';
  }
});
</script>

app/views/diyquan/_lanlan_quan_list.html.haml
#couponList.zk-list.clearfix
  - coupons.each do |coupon|
    = render partial: "diyquan/lanlan_quan_item", locals: {coupon: coupon}

app/views/diyquan/_quan_item.html.haml
- aaid = coupon['url'].match(/activityId=(\w*)/)
- aaid = aaid.nil? ? '' : aaid[1]
- buy_url = "/buy/#{coupon["item_id"]}/?activity_id=#{aaid}"
- seo_k = @seo_k.nil? ? '' : "#{@seo_k}_"
- strong_k = @keyword.nil? ? '' : @keyword
.zk-item
  .img-area
    %a{href: "/youhui/#{coupon['coupon_id']}/", title: "#{seo_k}#{coupon['title']}", target: "_blank"}
      .lq
        .lq-t
          .lq-t-d1 领优惠券
          .lq-t-d2 
            省
            %span #{coupon['gap_price']}
            元
        .lq-b
      %img.lazy{src: "", alt: "#{seo_k}#{coupon['title']}#{coupon['gap_price']}元优惠券", data: {original: "#{coupon['thumbnail_pic']}"}, style: "opacity: 1;"}

  %p.title-area.elli
    - if coupon['post_free'] == 1
      %span.post-free 包邮
    #{coupon['title'].gsub(strong_k, "<strong>#{strong_k}</strong>").html_safe}
  .raw-price-area
    现价 ￥#{coupon['raw_price']}
    %p.sold 已领 #{coupon['month_sales']} 张券
  .info
    .price-area
      %span.price 
        %span>￥
        %em.number-font #{coupon['coupon_price'].to_i}
        %em.decimal> .#{coupon['coupon_price'].to_s.sub(/\d+\./,'')}
        %i
    .buy-area
      %a{href: "#{buy_url}", target: "_blank"}
        %span.coupon-amount 去天猫
        %span.btn-title 火速领券
    .platform-area
      - if coupon["platform_id"] == 2
        %img{src: "http://7xlxny.com1.z0.glb.clouddn.com/zhekou/web/platform_tmall.png"}
        天猫
      - else 
        %img{src: "http://7xlxny.com1.z0.glb.clouddn.com/zhekou/web/platform_taobao.png"}
        淘宝

app/views/diyquan/_suggest_keywords.html.haml
- if keywords
  .hori-cate-area
    .hot-keywords
      .wrapper
        - keywords.each do |keyword|
          %a{href: "/zhekou/#{URI.encode(keyword)}/", title: "#{keyword}折扣优惠券"} #{keyword}

app/views/diyquan/_tb_quan_list.html.haml
#couponList.zk-list.clearfix
  - coupons.each do |coupon|
    = render partial: "diyquan/tb_quan_item", locals: {coupon: coupon}

app/views/diyquan/map_k.html.haml
- title(@title)
- head_desc(@description)
- keywords(@keywords)
- path(@path)
- mobile_url(@path)
- h1(@h1)

= render partial: "diyquan/header_fenlei_zhekou"
- @sks.each do |sk|
  - next if sk.sks.empty?
  = render partial: "diyquan/suggest_keywords", locals: {keywords: [sk.keyword] + sk.sks.split(',')}
.hori-cate-area
  .hot-keywords
    .wrapper
      - (1..83).to_a.each do |page|
        %a{href: "/map_k/#{page}/"} #{page}

= render partial: "diyquan/footer"

app/views/layouts/_ga_js_script.html.erb
<script>
ga('create', 'UA-96984648-1', 'auto');
ga('send', 'pageview', '<%= @path %>');
</script>

app/views/m_diyquan/_banners.html.haml
.banner-area.swiper-container.swiper-container-horizontal
  #bannerArea.swiper-wrapper
    %a{href: "",class: "swiper-slide"}
      %img.lazy{data: {original: ""}}

app/views/m_diyquan/_danpai_item.html.haml
- progress = (70..98).to_a.sample
- buy_url = "/buy/#{coupon["item_id"]}/?activity_id=#{coupon['url'].match(/activityId=(\w*)/)[1]}"
- seo_k = @seo_k.nil? ? '' : "#{@seo_k}_"
- strong_k = @keyword.nil? ? '' : @keyword
%a{href: "/youhui/#{coupon['coupon_id']}/", title: "#{seo_k}#{coupon['title']}",target: "_blank"}
  .coupon-card-v2
    .pic-area.lazy{data: {original: "#{coupon['thumbnail_pic']}"}}
    .info-area
      .info-top
        %p.title #{coupon['title'].gsub(strong_k, "<strong>#{strong_k}</strong>").html_safe}
        %p.stat
          - if coupon['platform_id'] == 2
            %span.platform.tmall
          - else
            %span.platform.taobao
          %span> 原价￥#{coupon['raw_price']}元
      .info-bottom
        .price-area
          %span.qhj 券后价
          %span.yen &nbsp;&nbsp;
          %span.price.number-font> #{coupon['coupon_price']}
          %span.quan-btn
            %em.number-font #{coupon['gap_price']}
            %span> 元券
        .progress-area
          %span.pro-desc 已领#{progress}%
          .pro-container
            .pro{style: "width: #{progress}%"}

app/views/m_diyquan/_shuangpai_item.html.haml
- progress = (60..98).to_a.sample
- aaid = coupon['url'].match(/activityId=(\w*)/)
- aaid = aaid.nil? ? '' : aaid[1]
- buy_url = "/buy/#{coupon["item_id"]}/?activity_id=#{aaid}"
- seo_k = @seo_k.nil? ? '' : "#{@seo_k}_"
- strong_k = @keyword.nil? ? '' : @keyword
%a{href: "/youhui/#{coupon['coupon_id']}/", title: "#{seo_k}#{coupon['title']}", target: "_blank"}
  .product-item-t2
    .pic.lazy{data: {original: "#{coupon['thumbnail_pic']}"}}
    %p.title
      - if coupon["post_free"] == 1
        %span.post-free 包邮
      #{coupon['title'].gsub(strong_k, "<strong>#{strong_k}</strong>").html_safe}
    .progress-area
      %p.pro-text 已领#{progress}%
      .pro-container
        .pro{data: {pro: "#{progress / 100.0}"}, style: "width:#{progress}%"}
    .price-area
      %p.gap-price
        %em.number-font #{coupon['gap_price']}
        %span> 元券
      .price
        %span> 券后价￥
        %em.number-font #{coupon['coupon_price']}

app/views/m_diyquan/_tb_shuangpai_item.html.haml
- progress = (60..98).to_a.sample
- buy_url = "/buy/#{coupon["num_iid"]}/?activity_id="
%a{href: "#{buy_url}", target: "_blank"}
  .product-item-t2
    .pic.lazy{data: {original: "#{coupon['pict_url']}"}}
    %p.title
      %span.post-free 包邮
      #{coupon["title"]}
    .progress-area
      %p.pro-text 已领#{progress}%
      .pro-container
        .pro{data: {pro: "#{progress / 100.0}"}, style: "width:#{progress}%"}
    .price-area
      %p.gap-price
        %em.number-font X
        %span> 元券
      .price
        %span> 券后价￥
        %em.number-font #{coupon['zk_final_price']}